
PROMPT .....................
PROMPT ....===GO_HORSE==....
PROMPT ..//             \\..
PROMPT .||    /\__       ||.
PROMPT .||    |  �\____  ||.
PROMPT .||   /|   ,___;) ||.
PROMPT .||   /|   |      ||.
PROMPT .||   /|   \      ||.
PROMPT ..\\  /|    \    //..
PROMPT ...\\__PROCESS__//...
PROMPT ....-------------....
PROMPT .....................
